import { Questionnaire } from "@/lib/test/types";
const SEVERITY_COLOR = {
  NORMAL: "#22c55e",
  INTERMEDIATE: "#a855f7",
  WARNING: "#3b82f6",
  MINOR: "#eab308",
  MAJOR: "#f97316",
  CRITICAL: "#ef4444",
} as const;
export type SEVERITY_COLOR =
  (typeof SEVERITY_COLOR)[keyof typeof SEVERITY_COLOR];

const questionnaires: Array<Questionnaire> = [
  {
    id: 0,
    name: "phq9",
    title: "우울증 선별검사(PHQ-9 검사)",
    image: "/images/test/phq9-logo.svg",
    description:
      "스스로 우울증의 증상을 간단히 평가하기 위한 도구입니다. 의사들이 환자들의 우울증 증상을 빠르게 스크리닝 하고 평가하는데 도움을 줄 수 있습니다.",
    instruction: "각 항목에 대해 최근 2주 동안 자신의 경험을 대답해주세요",
    version: 1,
    date: new Date(),
    questions: [
      {
        index: 0,
        description: "일 또는 여가 활동을 하는데 흥미나 즐거움을 느끼지 못함",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 방해 받지 않았다" },
          { index: 1, value: 1, answer: "며칠 동안 방해 받았다" },
          { index: 2, value: 2, answer: "7일 이상 방해 받았다" },
          { index: 3, value: 3, answer: "거의 매일 방해 받았다" },
        ],
      },
      {
        index: 1,
        description: "기분이 가라앉거나, 우울하거나, 희망이 없음",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 방해 받지 않았다" },
          { index: 1, value: 1, answer: "며칠 동안 방해 받았다" },
          { index: 2, value: 2, answer: "7일 이상 방해 받았다" },
          { index: 3, value: 3, answer: "거의 매일 방해 받았다" },
        ],
      },
      {
        index: 2,
        description:
          "잠이 들거나 계속 잠을 자는 것이 어려움, 또는 잠을 너무 많이 잠",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 방해 받지 않았다" },
          { index: 1, value: 1, answer: "며칠 동안 방해 받았다" },
          { index: 2, value: 2, answer: "7일 이상 방해 받았다" },
          { index: 3, value: 3, answer: "거의 매일 방해 받았다" },
        ],
      },
      {
        index: 3,
        description: "피곤하다고 느끼거나 기운이 거의 없음",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 방해 받지 않았다" },
          { index: 1, value: 1, answer: "며칠 동안 방해 받았다" },
          { index: 2, value: 2, answer: "7일 이상 방해 받았다" },
          { index: 3, value: 3, answer: "거의 매일 방해 받았다" },
        ],
      },
      {
        index: 4,
        description: "입맛이 없거나 혹은 과식을 함",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 방해 받지 않았다" },
          { index: 1, value: 1, answer: "며칠 동안 방해 받았다" },
          { index: 2, value: 2, answer: "7일 이상 방해 받았다" },
          { index: 3, value: 3, answer: "거의 매일 방해 받았다" },
        ],
      },
      {
        index: 5,
        description:
          "자신을 부정적으로 봄, 혹은 자신이 실패자라고 느끼거나 자신 또는 가족을 실망시킴",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 방해 받지 않았다" },
          { index: 1, value: 1, answer: "며칠 동안 방해 받았다" },
          { index: 2, value: 2, answer: "7일 이상 방해 받았다" },
          { index: 3, value: 3, answer: "거의 매일 방해 받았다" },
        ],
      },
      {
        index: 6,
        description:
          "신문을 읽거나 텔레비전 보는 것과 같은 일에 집중하는 것이 어려움",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 방해 받지 않았다" },
          { index: 1, value: 1, answer: "며칠 동안 방해 받았다" },
          { index: 2, value: 2, answer: "7일 이상 방해 받았다" },
          { index: 3, value: 3, answer: "거의 매일 방해 받았다" },
        ],
      },
      {
        index: 7,
        description:
          "다른 사람들이 주목할 정도로 너무 느리게 움직이거나 말을 함. 또는 반대로 평상시보다 많이 움직여서, 너무 안절부절 못하거나 들떠 있음",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 방해 받지 않았다" },
          { index: 1, value: 1, answer: "며칠 동안 방해 받았다" },
          { index: 2, value: 2, answer: "7일 이상 방해 받았다" },
          { index: 3, value: 3, answer: "거의 매일 방해 받았다" },
        ],
      },
      {
        index: 8,
        description:
          "자신이 죽는 것이 더 낫다고 생각하거나 어떤 식으로든 자신을 해칠 것이라고 생각함",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 방해 받지 않았다" },
          { index: 1, value: 1, answer: "며칠 동안 방해 받았다" },
          { index: 2, value: 2, answer: "7일 이상 방해 받았다" },
          { index: 3, value: 3, answer: "거의 매일 방해 받았다" },
        ],
      },
    ],
    groups: [
      {
        id: "group1",
        title: "우울증 심각도",
        description: "우울증이 얼마나 심한지에 대해서 나타내는 척도입니다",
        cutOffs: [
          {
            index: 0,
            end: 4,
            result: "우울증이 없습니다",
            description: "우울증이 없습니다",
            severityColor: SEVERITY_COLOR.NORMAL,
          },
          {
            index: 0,
            end: 9,
            result: "가벼운 우울증",
            description: "가벼운 우울증이 있을 가능성이 있습니다",
            severityColor: SEVERITY_COLOR.INTERMEDIATE,
          },
          {
            index: 0,
            end: 14,
            result: "중등도의 우울증",
            description: "중등도의 우울증이 있을 가능성이 있습니다",
            severityColor: SEVERITY_COLOR.WARNING,
          },
          {
            index: 0,
            end: 19,
            result: "상당히 심한 우울증",
            description: "상당히 심한 우울증이 있을 가능성이 있습니다",
            severityColor: SEVERITY_COLOR.MINOR,
          },
          {
            index: 1,
            end: 27,
            result: "매우 심한 우울증",
            description: "매우 심한 우울증이 있을 가능성이 있습니다",
            severityColor: SEVERITY_COLOR.MAJOR,
          },
        ],
      },
    ],
    relatedArticles: [
      "https://m.blog.naver.com/hearimclinic/223204500072",
      "https://m.blog.naver.com/hearimclinic/223171162693",
      "https://m.blog.naver.com/hearimclinic/223198118335",
    ],
    relatedTests: [
      "https://test.hearam.kr/test/cesd",
      "https://test.hearam.kr/test/pss",
      "https://test.hearam.kr/test/asrs",
      "https://test.hearam.kr/test/mdq",
      "https://test.hearam.kr/test/audit",
    ],
  },
  {
    id: 1,
    name: "cesd",
    title: "역학연구 우울척도(CES-D 검사)",
    image: "/images/test/cesd-logo.svg",
    description:
      "개인이 일상생활에서 느끼는 우울한 감정을 평가하는 도구입니다. 우울증의 경험이나 증상을 가진 개인들을 식별하고 이를 통해 정신건강 전문가들이 더 적절한 치료를 제공할 수 있도록 하는 것을 목표로 합니다",
    instruction:
      "다음과 같은 일들이 지난 일주일 동안 얼마나 자주 일어났었는지 답변해주세요",
    version: 1,
    date: new Date(),
    questions: [
      {
        index: 0,
        description: "평소에는 아무렇지도 않던 일들이 괴롭고 귀찮게 느껴진다",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "지난 일주일 동안 1일 미만" },
          { index: 1, value: 1, answer: "지난 일주일 동안 1~2일" },
          { index: 2, value: 2, answer: "지난 일주일 동안 3~4일" },
          { index: 3, value: 3, answer: "지난 일주일 동안 5~7일" },
        ],
      },
      {
        index: 1,
        description: "먹고 싶지 않고 식욕이 없었다",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "지난 일주일 동안 1일 미만" },
          { index: 1, value: 1, answer: "지난 일주일 동안 1~2일" },
          { index: 2, value: 2, answer: "지난 일주일 동안 3~4일" },
          { index: 3, value: 3, answer: "지난 일주일 동안 5~7일" },
        ],
      },
      {
        index: 2,
        description:
          "어느 누가 도와준다 하더라도 나의 울적한 기분을 떨쳐버릴 수 없을 것 같았다",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "지난 일주일 동안 1일 미만" },
          { index: 1, value: 1, answer: "지난 일주일 동안 1~2일" },
          { index: 2, value: 2, answer: "지난 일주일 동안 3~4일" },
          { index: 3, value: 3, answer: "지난 일주일 동안 5~7일" },
        ],
      },
      {
        index: 3,
        description: "무슨 일을 하든 정신을 집중하기가 힘들었다",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "지난 일주일 동안 1일 미만" },
          { index: 1, value: 1, answer: "지난 일주일 동안 1~2일" },
          { index: 2, value: 2, answer: "지난 일주일 동안 3~4일" },
          { index: 3, value: 3, answer: "지난 일주일 동안 5~7일" },
        ],
      },
      {
        index: 4,
        description: "비교적 잘 지냈다",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 3, answer: "지난 일주일 동안 1일 미만" },
          { index: 1, value: 2, answer: "지난 일주일 동안 1~2일" },
          { index: 2, value: 1, answer: "지난 일주일 동안 3~4일" },
          { index: 3, value: 0, answer: "지난 일주일 동안 5~7일" },
        ],
      },
      {
        index: 5,
        description: "상당히 우울했다",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "지난 일주일 동안 1일 미만" },
          { index: 1, value: 1, answer: "지난 일주일 동안 1~2일" },
          { index: 2, value: 2, answer: "지난 일주일 동안 3~4일" },
          { index: 3, value: 3, answer: "지난 일주일 동안 5~7일" },
        ],
      },
      {
        index: 6,
        description: "모든 일들이 힘들게 느껴졌다",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "지난 일주일 동안 1일 미만" },
          { index: 1, value: 1, answer: "지난 일주일 동안 1~2일" },
          { index: 2, value: 2, answer: "지난 일주일 동안 3~4일" },
          { index: 3, value: 3, answer: "지난 일주일 동안 5~7일" },
        ],
      },
      {
        index: 7,
        description: "앞일이 암담하게 느껴졌다",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "지난 일주일 동안 1일 미만" },
          { index: 1, value: 1, answer: "지난 일주일 동안 1~2일" },
          { index: 2, value: 2, answer: "지난 일주일 동안 3~4일" },
          { index: 3, value: 3, answer: "지난 일주일 동안 5~7일" },
        ],
      },
      {
        index: 8,
        description: "지금까지의 내 인생은 실패작이라는 생각이 들었다",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "지난 일주일 동안 1일 미만" },
          { index: 1, value: 1, answer: "지난 일주일 동안 1~2일" },
          { index: 2, value: 2, answer: "지난 일주일 동안 3~4일" },
          { index: 3, value: 3, answer: "지난 일주일 동안 5~7일" },
        ],
      },
      {
        index: 9,
        description: "적어도 보통 사람들만큼의 능력은 있었다고 생각 한다.",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 3, answer: "지난 일주일 동안 1일 미만" },
          { index: 1, value: 2, answer: "지난 일주일 동안 1~2일" },
          { index: 2, value: 1, answer: "지난 일주일 동안 3~4일" },
          { index: 3, value: 0, answer: "지난 일주일 동안 5~7일" },
        ],
      },
      {
        index: 10,
        description: "잠을 설쳤다(잠을 잘 이루지 못했다)",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "지난 일주일 동안 1일 미만" },
          { index: 1, value: 1, answer: "지난 일주일 동안 1~2일" },
          { index: 2, value: 2, answer: "지난 일주일 동안 3~4일" },
          { index: 3, value: 3, answer: "지난 일주일 동안 5~7일" },
        ],
      },
      {
        index: 11,
        description: "두려움을 느꼈다",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "지난 일주일 동안 1일 미만" },
          { index: 1, value: 1, answer: "지난 일주일 동안 1~2일" },
          { index: 2, value: 2, answer: "지난 일주일 동안 3~4일" },
          { index: 3, value: 3, answer: "지난 일주일 동안 5~7일" },
        ],
      },
      {
        index: 12,
        description: "평소에 비해 말수가 적었다",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "지난 일주일 동안 1일 미만" },
          { index: 1, value: 1, answer: "지난 일주일 동안 1~2일" },
          { index: 2, value: 2, answer: "지난 일주일 동안 3~4일" },
          { index: 3, value: 3, answer: "지난 일주일 동안 5~7일" },
        ],
      },
      {
        index: 13,
        description: "세상에 홀로 있는 듯한 외로움을 느꼈다",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "지난 일주일 동안 1일 미만" },
          { index: 1, value: 1, answer: "지난 일주일 동안 1~2일" },
          { index: 2, value: 2, answer: "지난 일주일 동안 3~4일" },
          { index: 3, value: 3, answer: "지난 일주일 동안 5~7일" },
        ],
      },
      {
        index: 14,
        description: "큰 불만 없이 생활 했다",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 3, answer: "지난 일주일 동안 1일 미만" },
          { index: 1, value: 2, answer: "지난 일주일 동안 1~2일" },
          { index: 2, value: 1, answer: "지난 일주일 동안 3~4일" },
          { index: 3, value: 0, answer: "지난 일주일 동안 5~7일" },
        ],
      },
      {
        index: 15,
        description: "사람들이 나에게 차갑게 대하는 것 같았다",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "지난 일주일 동안 1일 미만" },
          { index: 1, value: 1, answer: "지난 일주일 동안 1~2일" },
          { index: 2, value: 2, answer: "지난 일주일 동안 3~4일" },
          { index: 3, value: 3, answer: "지난 일주일 동안 5~7일" },
        ],
      },
      {
        index: 16,
        description: "갑자기 울음이 나왔다",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "지난 일주일 동안 1일 미만" },
          { index: 1, value: 1, answer: "지난 일주일 동안 1~2일" },
          { index: 2, value: 2, answer: "지난 일주일 동안 3~4일" },
          { index: 3, value: 3, answer: "지난 일주일 동안 5~7일" },
        ],
      },
      {
        index: 17,
        description: "마음이 슬펏다",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "지난 일주일 동안 1일 미만" },
          { index: 1, value: 1, answer: "지난 일주일 동안 1~2일" },
          { index: 2, value: 2, answer: "지난 일주일 동안 3~4일" },
          { index: 3, value: 3, answer: "지난 일주일 동안 5~7일" },
        ],
      },
      {
        index: 18,
        description: "사람들이 나를 싫어하는 것 같았다",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "지난 일주일 동안 1일 미만" },
          { index: 1, value: 1, answer: "지난 일주일 동안 1~2일" },
          { index: 2, value: 2, answer: "지난 일주일 동안 3~4일" },
          { index: 3, value: 3, answer: "지난 일주일 동안 5~7일" },
        ],
      },
      {
        index: 19,
        description: "도무지 뭘 해 나갈 엄두가 나지 않았다",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "지난 일주일 동안 1일 미만" },
          { index: 1, value: 1, answer: "지난 일주일 동안 1~2일" },
          { index: 2, value: 2, answer: "지난 일주일 동안 3~4일" },
          { index: 3, value: 3, answer: "지난 일주일 동안 5~7일" },
        ],
      },
    ],
    groups: [
      {
        id: "group1",
        title: "우울증 심각도",
        description:
          "우울증이 있는지 여부에 대해서 알려주는 척도이며 16점 이상부터 우울증이 존재할 가능성이 있는 것으로 판단합니다",
        cutOffs: [
          {
            index: 0,
            end: 15,
            result: "우울증이 없음",
            description:
              "척도 검사결과로 판정했을 때 우울증 가지고 있을 가능성이 낮습니다",
            severityColor: SEVERITY_COLOR.NORMAL,
          },
          {
            index: 1,
            end: 60,
            result: "우울증이 있음",
            description:
              "척도 검사결과로 판정했을 때 우울증을 가지고 있을 가능성이 높습니다",
            severityColor: SEVERITY_COLOR.INTERMEDIATE,
          },
        ],
      },
    ],
    relatedArticles: [
      "https://m.blog.naver.com/hearimclinic/223204500072",
      "https://m.blog.naver.com/hearimclinic/223171162693",
      "https://m.blog.naver.com/hearimclinic/223198118335",
    ],
    relatedTests: [
      "https://test.hearam.kr/test/phq9",
      "https://test.hearam.kr/test/pss",
      "https://test.hearam.kr/test/asrs",
      "https://test.hearam.kr/test/mdq",
      "https://test.hearam.kr/test/audit",
    ],
  },
  {
    id: 2,
    name: "pss",
    title: "지각된 스트레스 척도(Perceived Stress Scale)",
    image: "/images/test/pss-logo.svg",
    description:
      "스트레스 수준을 측정하고 평가하기위한 평가도구입니다. 피험자가 스트레스를 어떻게 인식하고 경험하는 지를 평가하여 사람들의 스트레스 수준을 평가하는데 유용합니다.",
    instruction:
      "지난 한 달 동안 당신의 감정에 대한 질문입니다. 각 질문에 대해 얼마나 자주 그러했는지 선택해주세요",
    version: 1,
    date: new Date(),
    questions: [
      {
        index: 0,
        description:
          "예상치 않게 생긴 일 때문에 속상한 적이 얼마나 자주 있었습니까?",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 없었다" },
          { index: 1, value: 1, answer: "거의 없었다" },
          { index: 2, value: 2, answer: "가끔 있었다" },
          { index: 3, value: 3, answer: "자주 있었다" },
          { index: 4, value: 4, answer: "매우 자주 있었다" },
        ],
      },
      {
        index: 1,
        description:
          "중요한 일을 조절할 수 없다고 느낀 적이 얼마나 자주 있었습니까?",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 없었다" },
          { index: 1, value: 1, answer: "거의 없었다" },
          { index: 2, value: 2, answer: "가끔 있었다" },
          { index: 3, value: 3, answer: "자주 있었다" },
          { index: 4, value: 4, answer: "매우 자주 있었다" },
        ],
      },
      {
        index: 2,
        description:
          "불안하고 스트레스 받았다고 느낀 적이 얼마나 자주 있었습니까?",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 없었다" },
          { index: 1, value: 1, answer: "거의 없었다" },
          { index: 2, value: 2, answer: "가끔 있었다" },
          { index: 3, value: 3, answer: "자주 있었다" },
          { index: 4, value: 4, answer: "매우 자주 있었다" },
        ],
      },
      {
        index: 3,
        description:
          "개인적인 문제를 잘 처리할 수 있다고 자신감을 가진 적이 얼마나 자주 있었습니까?",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 없었다" },
          { index: 1, value: 1, answer: "거의 없었다" },
          { index: 2, value: 2, answer: "가끔 있었다" },
          { index: 3, value: 3, answer: "자주 있었다" },
          { index: 4, value: 4, answer: "매우 자주 있었다" },
        ],
      },
      {
        index: 4,
        description:
          "일이 내 뜻대로 진행되고 있다고 느낀 적이 얼마나 자주 있었습니까?",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 없었다" },
          { index: 1, value: 1, answer: "거의 없었다" },
          { index: 2, value: 2, answer: "가끔 있었다" },
          { index: 3, value: 3, answer: "자주 있었다" },
          { index: 4, value: 4, answer: "매우 자주 있었다" },
        ],
      },
      {
        index: 5,
        description:
          "자신이 해야 할 모든 일에 잘 대처할 수 없었던 적이 얼마나 자주 있었습니까?",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 없었다" },
          { index: 1, value: 1, answer: "거의 없었다" },
          { index: 2, value: 2, answer: "가끔 있었다" },
          { index: 3, value: 3, answer: "자주 있었다" },
          { index: 4, value: 4, answer: "매우 자주 있었다" },
        ],
      },
      {
        index: 6,
        description:
          "일상에서 짜증나는 것을 잘 조절할 수 있었던 적이 얼마나 자주 있었습니까?",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 없었다" },
          { index: 1, value: 1, answer: "거의 없었다" },
          { index: 2, value: 2, answer: "가끔 있었다" },
          { index: 3, value: 3, answer: "자주 있었다" },
          { index: 4, value: 4, answer: "매우 자주 있었다" },
        ],
      },
      {
        index: 7,
        description:
          "자신이 일을 잘 해냈다고 느낀 적이 얼마나 자주 있었습니까?",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 없었다" },
          { index: 1, value: 1, answer: "거의 없었다" },
          { index: 2, value: 2, answer: "가끔 있었다" },
          { index: 3, value: 3, answer: "자주 있었다" },
          { index: 4, value: 4, answer: "매우 자주 있었다" },
        ],
      },
      {
        index: 8,
        description:
          "자신의 능력으로는 어떻게 해 볼 수 없는 일 때문에 화가 난 적이 얼마나 자주 있었습니까?",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 없었다" },
          { index: 1, value: 1, answer: "거의 없었다" },
          { index: 2, value: 2, answer: "가끔 있었다" },
          { index: 3, value: 3, answer: "자주 있었다" },
          { index: 4, value: 4, answer: "매우 자주 있었다" },
        ],
      },
      {
        index: 9,
        description:
          "어려운 일이 너무 많아져서 극복할 수 없다고 느낀 적이 얼마나 자주 있었습니까?",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 없었다" },
          { index: 1, value: 1, answer: "거의 없었다" },
          { index: 2, value: 2, answer: "가끔 있었다" },
          { index: 3, value: 3, answer: "자주 있었다" },
          { index: 4, value: 4, answer: "매우 자주 있었다" },
        ],
      },
    ],
    groups: [
      {
        id: "group1",
        title: "스트레스 심각도",
        description: "우울증이 얼마나 심한지에 대해서 나타내는 척도입니다",
        cutOffs: [
          {
            index: 0,
            end: 13,
            result: "낮은 스트레스 수준",
            description: "스트레스 수준이 낮습니다",
            severityColor: SEVERITY_COLOR.NORMAL,
          },
          {
            index: 1,
            end: 26,
            result: "상당한 스트레스 수준",
            description: "스트레스를 상당히 느끼고 있습니다",
            severityColor: SEVERITY_COLOR.INTERMEDIATE,
          },
          {
            index: 2,
            end: 40,
            result: "심한 스트레스 수준",
            description: "심한 스트레스를 느끼고 있습니다",
            severityColor: SEVERITY_COLOR.MAJOR,
          },
        ],
      },
    ],
    relatedArticles: [
      "https://m.blog.naver.com/hearimclinic/223153554819",
      "https://m.blog.naver.com/hearimclinic/223253957818",
      "https://m.blog.naver.com/hearimclinic/223198118335",
    ],
    relatedTests: [
      "https://test.hearam.kr/test/phq9",
      "https://test.hearam.kr/test/cesd",
      "https://test.hearam.kr/test/asrs",
      "https://test.hearam.kr/test/mdq",
      "https://test.hearam.kr/test/audit",
    ],
  },
  {
    id: 3,
    name: "asrs",
    title: "성인 ADHD 자가 보고 척도(Adult ADHD Self-Report Scale)",
    image: "/images/test/asrs-logo.svg",
    description:
      "성인기까지 지속되고 있는 ADHD(성인 ADHD)를 찾아내기 위한 평가도구 입니다. 이 검사를 통해서 성인 ADHD를 가지고 있을 가능성이 높은 사람들을 선별할 수 있습니다.",
    instruction:
      "지난 6개월 동안 어떻게 느끼고 행동하였는지를 가장 잘 설명하는 것을 선택해 주세요",
    version: 1,
    date: new Date(),
    questions: [
      {
        index: 0,
        description:
          "어떤 일의 어려운 부분은 끝내 놓고, 그 일을 마무리를 짓지 못해 곤란을 겪은 적이 있습니까?",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 그렇지 않다" },
          { index: 1, value: 0, answer: "거의 그렇지 않다(드물게 그렇다)" },
          { index: 2, value: 1, answer: "약간 혹은 가끔 그렇다" },
          { index: 3, value: 1, answer: "자주 그렇다" },
          { index: 4, value: 1, answer: "매우 자주 그렇다" },
        ],
      },
      {
        index: 1,
        description:
          "체계가 필요한 일을 해야 할 때 순서대로 진행하기 어려운 경우가 있습니까?",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 그렇지 않다" },
          { index: 1, value: 0, answer: "거의 그렇지 않다(드물게 그렇다)" },
          { index: 2, value: 1, answer: "약간 혹은 가끔 그렇다" },
          { index: 3, value: 1, answer: "자주 그렇다" },
          { index: 4, value: 1, answer: "매우 자주 그렇다" },
        ],
      },
      {
        index: 2,
        description:
          "약속이나 해야 할 일을 잊어버려 곤란을 겪은 적이 있습니까?",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 그렇지 않다" },
          { index: 1, value: 0, answer: "거의 그렇지 않다(드물게 그렇다)" },
          { index: 2, value: 1, answer: "약간 혹은 가끔 그렇다" },
          { index: 3, value: 1, answer: "자주 그렇다" },
          { index: 4, value: 1, answer: "매우 자주 그렇다" },
        ],
      },
      {
        index: 3,
        description: "골치 아픈 일은 피하거나 미루는 경우가 있습니까?",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 그렇지 않다" },
          { index: 1, value: 0, answer: "거의 그렇지 않다(드물게 그렇다)" },
          { index: 2, value: 0, answer: "약간 혹은 가끔 그렇다" },
          { index: 3, value: 1, answer: "자주 그렇다" },
          { index: 4, value: 1, answer: "매우 자주 그렇다" },
        ],
      },
      {
        index: 4,
        description:
          "오래 앉아 있을 때, 손을 만지작 거리거나 발을 꼼지락 거리는 경우가 있습니까?",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 그렇지 않다" },
          { index: 1, value: 0, answer: "거의 그렇지 않다(드물게 그렇다)" },
          { index: 2, value: 0, answer: "약간 혹은 가끔 그렇다" },
          { index: 3, value: 1, answer: "자주 그렇다" },
          { index: 4, value: 1, answer: "매우 자주 그렇다" },
        ],
      },
      {
        index: 5,
        description:
          "마치 모터가 달린 것 처럼, 과도하게 혹은 멈출 수 없이 활동을 하는 경우가 있습니까?",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 그렇지 않다" },
          { index: 1, value: 0, answer: "거의 그렇지 않다(드물게 그렇다)" },
          { index: 2, value: 0, answer: "약간 혹은 가끔 그렇다" },
          { index: 3, value: 1, answer: "자주 그렇다" },
          { index: 4, value: 1, answer: "매우 자주 그렇다" },
        ],
      },
      {
        index: 6,
        description:
          "지루하고 어려운 일을 할 때, 부주의해서 실수를 하는 경우가 있습니까?",
        group: "group2",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 그렇지 않다" },
          { index: 1, value: 0, answer: "거의 그렇지 않다(드물게 그렇다)" },
          { index: 2, value: 0, answer: "약간 혹은 가끔 그렇다" },
          { index: 3, value: 1, answer: "자주 그렇다" },
          { index: 4, value: 1, answer: "매우 자주 그렇다" },
        ],
      },
      {
        index: 7,
        description:
          "지루하고 반복적인 일을 할 때, 주의 집중이 힘든 경우가 있습니까?",
        group: "group2",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 그렇지 않다" },
          { index: 1, value: 0, answer: "거의 그렇지 않다(드물게 그렇다)" },
          { index: 2, value: 0, answer: "약간 혹은 가끔 그렇다" },
          { index: 3, value: 1, answer: "자주 그렇다" },
          { index: 4, value: 1, answer: "매우 자주 그렇다" },
        ],
      },
      {
        index: 8,
        description:
          "대화 중, 특히 상대방이 당신에게 직접적으로 말하고 있을 때에도, 집중하기 힘든 경우가 있습니까?",
        group: "group2",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 그렇지 않다" },
          { index: 1, value: 0, answer: "거의 그렇지 않다(드물게 그렇다)" },
          { index: 2, value: 1, answer: "약간 혹은 가끔 그렇다" },
          { index: 3, value: 1, answer: "자주 그렇다" },
          { index: 4, value: 1, answer: "매우 자주 그렇다" },
        ],
      },
      {
        index: 9,
        description:
          "집이나 직장에서 물건을 엉뚱한 곳에 두거나 어디에 두었는지 찾기 어려운 경우가 있습니까?",
        group: "group2",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 그렇지 않다" },
          { index: 1, value: 0, answer: "거의 그렇지 않다(드물게 그렇다)" },
          { index: 2, value: 0, answer: "약간 혹은 가끔 그렇다" },
          { index: 3, value: 1, answer: "자주 그렇다" },
          { index: 4, value: 1, answer: "매우 자주 그렇다" },
        ],
      },
      {
        index: 10,
        description:
          "주변에서 벌어지는 일이나 소음 때문에 주의가 산만해 지는 경우가 있습니까?",
        group: "group2",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 그렇지 않다" },
          { index: 1, value: 0, answer: "거의 그렇지 않다(드물게 그렇다)" },
          { index: 2, value: 0, answer: "약간 혹은 가끔 그렇다" },
          { index: 3, value: 1, answer: "자주 그렇다" },
          { index: 4, value: 1, answer: "매우 자주 그렇다" },
        ],
      },
      {
        index: 11,
        description:
          "회의나 다른 사회적 상황에서 계속 앉아 있어야 함에도 잠깐씩 자리를 뜨는 경우가 있습니까?",
        group: "group2",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 그렇지 않다" },
          { index: 1, value: 0, answer: "거의 그렇지 않다(드물게 그렇다)" },
          { index: 2, value: 1, answer: "약간 혹은 가끔 그렇다" },
          { index: 3, value: 1, answer: "자주 그렇다" },
          { index: 4, value: 1, answer: "매우 자주 그렇다" },
        ],
      },
      {
        index: 12,
        description: "안절부절 못하거나 조바심하는 경우가 있습니까?",
        group: "group2",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 그렇지 않다" },
          { index: 1, value: 0, answer: "거의 그렇지 않다(드물게 그렇다)" },
          { index: 2, value: 0, answer: "약간 혹은 가끔 그렇다" },
          { index: 3, value: 1, answer: "자주 그렇다" },
          { index: 4, value: 1, answer: "매우 자주 그렇다" },
        ],
      },
      {
        index: 13,
        description:
          "혼자 쉬고 있을 때, 긴장을 풀거나 마음을 편하게 갖기 어려운 경우가 있습니까?",
        group: "group2",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 그렇지 않다" },
          { index: 1, value: 0, answer: "거의 그렇지 않다(드물게 그렇다)" },
          { index: 2, value: 0, answer: "약간 혹은 가끔 그렇다" },
          { index: 3, value: 1, answer: "자주 그렇다" },
          { index: 4, value: 1, answer: "매우 자주 그렇다" },
        ],
      },
      {
        index: 14,
        description:
          "사회적 상황에서 나 혼자 말을 너무 많이 한다고 느끼는 경우가 있습니까?",
        group: "group2",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 그렇지 않다" },
          { index: 1, value: 0, answer: "거의 그렇지 않다(드물게 그렇다)" },
          { index: 2, value: 0, answer: "약간 혹은 가끔 그렇다" },
          { index: 3, value: 1, answer: "자주 그렇다" },
          { index: 4, value: 1, answer: "매우 자주 그렇다" },
        ],
      },
      {
        index: 15,
        description:
          "대화 도중 상대방이 말을 끝내기 전에 끼어들어 상대방의 말을 끊는 경우가 있습니까?",
        group: "group2",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 그렇지 않다" },
          { index: 1, value: 0, answer: "거의 그렇지 않다(드물게 그렇다)" },
          { index: 2, value: 1, answer: "약간 혹은 가끔 그렇다" },
          { index: 3, value: 1, answer: "자주 그렇다" },
          { index: 4, value: 1, answer: "매우 자주 그렇다" },
        ],
      },
      {
        index: 16,
        description:
          "차례를 지켜야 하는 상황에서 자신의 차례를 기다리는 것이 어려운 경우가 있습니까?",
        group: "group2",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 그렇지 않다" },
          { index: 1, value: 0, answer: "거의 그렇지 않다(드물게 그렇다)" },
          { index: 2, value: 0, answer: "약간 혹은 가끔 그렇다" },
          { index: 3, value: 1, answer: "자주 그렇다" },
          { index: 4, value: 1, answer: "매우 자주 그렇다" },
        ],
      },
      {
        index: 17,
        description:
          "다른 사람이 바쁘게 일할 때, 방해되는 행동을 하는 경우가 있습니까?",
        group: "group2",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 그렇지 않다" },
          { index: 1, value: 0, answer: "거의 그렇지 않다(드물게 그렇다)" },
          { index: 2, value: 1, answer: "약간 혹은 가끔 그렇다" },
          { index: 3, value: 1, answer: "자주 그렇다" },
          { index: 4, value: 1, answer: "매우 자주 그렇다" },
        ],
      },
    ],
    groups: [
      {
        id: "group1",
        title: "성인 ADHD 가능성",
        description: "성인 ADHD을 가지고 있을 확률을 보여주는 지표입니다",
        cutOffs: [
          {
            index: 0,
            end: 3,
            result: "낮은 성인 ADHD 가능성",
            description: "성인 ADHD 가능성이 낮습니다",
            severityColor: SEVERITY_COLOR.NORMAL,
          },
          {
            index: 1,
            end: 6,
            result: "높은 성인 ADHD 가능성",
            description: "성인 ADHD 가능성이 높습니다",
            severityColor: SEVERITY_COLOR.INTERMEDIATE,
          },
        ],
      },
      {
        id: "group2",
        title: "성인 ADHD 심각도",
        description: "성인 ADHD 심각도를 나타냅니다.",
        cutOffs: [
          {
            index: 0,
            end: 12,
            result: "성인 ADHD 심각도",
            description: "점수가 높을수록 ADHD증상이 심할 수 있습니다",
            severityColor: SEVERITY_COLOR.INTERMEDIATE,
          },
        ],
      },
    ],
    relatedArticles: [
      "https://m.blog.naver.com/hearimclinic/223150583133",
      "https://m.blog.naver.com/hearimclinic/223149999126",
      "https://m.blog.naver.com/hearimclinic/223140172659",
    ],
    relatedTests: [
      "https://test.hearam.kr/test/phq9",
      "https://test.hearam.kr/test/cesd",
      "https://test.hearam.kr/test/pss",
      "https://test.hearam.kr/test/asrs",
      "https://test.hearam.kr/test/audit",
    ],
  },
  {
    id: 4,
    name: "mdq",
    title: "기분장애 질문지(Mood Disorder Questionnaire)",
    image: "/images/test/mdq-logo.svg",
    description:
      "조울병(양극성장애)를 가지고 있는지 여부를 스스로 검사해볼 수 있는 검사지입니다. 이 도구만으로 양극성장애를 진단할수는 없으나 이상소견이 있다면 전문의의 진단이 도움이 될 수 있습니다.",
    instruction:
      "당신을 가장 잘 설명한다고 느끼는 답변을 골라주세요. 최대한 자신을 잘 설명한다고 느끼는 답변을 골라주세요",
    version: 1,
    date: new Date(),
    questions: [
      {
        index: 0,
        description:
          "현재까지 살아오면서 과도하게 기분이 좋거나 들떠서 다른 사람과 트러블이 있었던 기간이 있었습니까?",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "그렇지 않다" },
          { index: 1, value: 1 / 13, answer: "그렇다" },
        ],
      },
      {
        index: 1,
        description:
          "현재까지 살아오면서 과하게 예민해져서 다른사람들과 싸우거나 논쟁을 벌였던 기간이 있었습니까?",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "그렇지 않다" },
          { index: 1, value: 1 / 13, answer: "그렇다" },
        ],
      },
      {
        index: 2,
        description:
          "현재까지 살아오면서 평소보다 자신감이 넘쳤던 기간이 있었습니까",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "그렇지 않다" },
          { index: 1, value: 1 / 13, answer: "그렇다" },
        ],
      },
      {
        index: 3,
        description:
          "현재까지 살아오면서 평소보다 잠이 줄고 잠을 자지 않아도 괜찮았던 기간이 있었습니까?",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "그렇지 않다" },
          { index: 1, value: 1 / 13, answer: "그렇다" },
        ],
      },
      {
        index: 4,
        description:
          "현재까지 살아오면서 평소보다 말이 많고 빨랐던 기간이 있었습니까?",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "그렇지 않다" },
          { index: 1, value: 1 / 13, answer: "그렇다" },
        ],
      },
      {
        index: 5,
        description:
          "현재까지 살아오면서 생각의 속도가 매우 빨라지거나 생각의 속도를 늦출 것 같지 못할것 같은 기간이 있었습니까?",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "그렇지 않다" },
          { index: 1, value: 1 / 13, answer: "그렇다" },
        ],
      },
      {
        index: 6,
        description:
          "현재까지 살아오면서 쉽게 주의가 흩어지거나 집중하는데 문제가 있었던 기간이 있었습니까?",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "그렇지 않다" },
          { index: 1, value: 1 / 13, answer: "그렇다" },
        ],
      },
      {
        index: 7,
        description:
          "현재까지 살아오면서 평소보다 훨씬 더 에너지가 넘쳤던 기간이 있었습니까?",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "그렇지 않다" },
          { index: 1, value: 1 / 13, answer: "그렇다" },
        ],
      },
      {
        index: 8,
        description:
          "현재까지 살아오면서 평소보다 훨씬 더 활발하거나 많은일을 해냈던 기간이 있었습니까?",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "그렇지 않다" },
          { index: 1, value: 1 / 13, answer: "그렇다" },
        ],
      },
      {
        index: 9,
        description:
          "현재까지 살아오면서 한밤중에 친구에게 전화하는 것 처럼 평소보다 훨씬 외향적이었던 기간이 있었습니까?",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "그렇지 않다" },
          { index: 1, value: 1 / 13, answer: "그렇다" },
        ],
      },
      {
        index: 10,
        description:
          "현재까지 살아오면서 평소보다 성관계에 몰두했던 기간이 있었습니까?",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "그렇지 않다" },
          { index: 1, value: 1 / 13, answer: "그렇다" },
        ],
      },
      {
        index: 11,
        description:
          "현재까지 살아오면서 평소와는 다르거나 다른사람들이 생각하기에 과하거나, 바보같건, 위험하다고 여길만한 일들을 벌였던 기간이 있었습니까?",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "그렇지 않다" },
          { index: 1, value: 1 / 13, answer: "그렇다" },
        ],
      },
      {
        index: 12,
        description:
          "현재까지 살아오면서 돈을 평소보다 너무 많이써서 스스로나 가족이 곤경에 처햇던 기간이 있습니까?",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "그렇지 않다" },
          { index: 1, value: 1 / 13, answer: "그렇다" },
        ],
      },
      {
        index: 13,
        description:
          "위에서의 질문들 중 '그렇다'가 하나 이상 존재한다면 그것들은 같은 기간에 발생하였던 것입니까?",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "그렇지 않다" },
          { index: 1, value: 1, answer: "그렇다" },
        ],
      },
      {
        index: 14,
        description:
          "위에서 언급한 사건들이 발생한 기간동안 당신에게 발생한 가족, 금전, 법적인 문제, 언쟁, 또는 싸움의 심각도는 어느정도였습니까?",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "문제가 없었다" },
          { index: 1, value: 0, answer: "약간의 문제가 있었다" },
          { index: 2, value: 1, answer: "상당한 문제가 있었다" },
          { index: 3, value: 1, answer: "심각한 문제가 있었다" },
        ],
      },
      {
        index: 15,
        description:
          "가족들 이나 친척들(자녀, 형제, 부모, 조부모, 삼촌 및 숙모) 중 조울병 또는 양극성 장애를 진단받은 사람이 있습니까?",
        group: "group2",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "그렇지 않다" },
          { index: 1, value: 1, answer: "그렇다" },
        ],
      },
      {
        index: 16,
        description:
          "의료인이 당신에게 조울병이나 양극성 장애가 있었다는 이야기를 한 적이 있습니까?",
        group: "group3",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "그렇지 않다" },
          { index: 1, value: 1, answer: "그렇다" },
        ],
      },
    ],
    groups: [
      {
        id: "group1",
        title: "조울병 또는 양극성 장애의 가능성",
        description:
          "조울병 또는 양극성 장애가 있을 가능성을 보여주는 지표입니다",
        cutOffs: [
          {
            index: 0,
            end: 2 + 6 / 13,
            result: "낮은 양극성 장애의 가능성",
            description:
              "조울병 또는 양극성 장애를 가지고 있을 가능성이 낮습니다",
            severityColor: SEVERITY_COLOR.NORMAL,
          },
          {
            index: 1,
            end: 3,
            result: "높은 양극성 장애의 가능성",
            description:
              "조울병 또는 양극성 장애를 가지고 있을 가능성이 높습니다",
            severityColor: SEVERITY_COLOR.INTERMEDIATE,
          },
        ],
      },
      {
        id: "group2",
        title: "조울병 또는 양극성 장애의 가족력",
        description:
          "가족력이 있으면 진단 확률이 높아지지만 이 지표의 의료인에게 받아야 합니다",
        cutOffs: [
          {
            index: 0,
            end: 0,
            result: "가족력 없음",
            description: "조울병 또는 양극성 장애의 가족력이 없습니다",
            severityColor: SEVERITY_COLOR.NORMAL,
          },
          {
            index: 1,
            end: 1,
            result: "가족력 있음",
            description: "조울병 또는 양극성 장애의 가족력이 있습니다",
            severityColor: SEVERITY_COLOR.INTERMEDIATE,
          },
        ],
      },
      {
        id: "group3",
        title: "조울병 또는 양극성 장애의 과거력",
        description:
          "과거에 조울병 또는 양극성 장애가 있었다는 이야기를 들은적이 있다는 이야기지만 이 지표의 해석은 의료인의 도움을 받아야 합니다",
        cutOffs: [
          {
            index: 0,
            end: 0,
            result: "과거력 없음",
            description: "조울병 또는 양극성 장애의 과거력이 없습니다",
            severityColor: SEVERITY_COLOR.NORMAL,
          },
          {
            index: 1,
            end: 1,
            result: "과거력 있음",
            description: "조울병 또는 양극성 장애의 과거력이 있습니다",
            severityColor: SEVERITY_COLOR.INTERMEDIATE,
          },
        ],
      },
    ],
    relatedArticles: [
      "https://m.blog.naver.com/hearimclinic/223273793744",
      "https://m.blog.naver.com/hearimclinic/223140172659",
      "https://m.blog.naver.com/hearimclinic/223204500072",
    ],
    relatedTests: [
      "https://test.hearam.kr/test/phq9",
      "https://test.hearam.kr/test/cesd",
      "https://test.hearam.kr/test/pss",
      "https://test.hearam.kr/test/asrs",
    ],
  },
  {
    id: 5,
    name: "audit",
    title: "알코올 사용장애 선별검사(Alcohol Use Disorder Identification Test)",
    image: "/images/test/audit-logo.svg",
    description:
      "현재 알코올 의존이 있는지 여부를 검사할 수 있는 검사지 입니다.",
    instruction:
      "자신의 음주 습관에 대해서 아래의 질문에 답변해 주세요. 한잔의 기준은 술의 종류에 따라 다를 수 있지만 소주 1/3병 또는 맥주 한캔(355ml) 정도로 보시면 됩니다",
    version: 1,
    date: new Date(),
    questions: [
      {
        index: 0,
        description: "알코올 음료를 얼마나 자주 마십니까?",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "마시지 않음" },
          { index: 1, value: 1, answer: "월 1회 또는 미만" },
          { index: 2, value: 2, answer: "월 2~4회" },
          { index: 3, value: 3, answer: "주 2 ~ 3회" },
          { index: 4, value: 4, answer: "주 4회 이상" },
        ],
      },
      {
        index: 1,
        description: "술을 마실 때 보통 알코올 음료를 몇잔 정도 마십니까?",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "0 ~ 2 잔" },
          { index: 1, value: 1, answer: "3 ~ 4 잔" },
          { index: 2, value: 2, answer: "5 ~ 6 잔" },
          { index: 3, value: 3, answer: "7 ~ 9 잔" },
          { index: 4, value: 4, answer: "10 잔 이상" },
        ],
      },
      {
        index: 2,
        description: "한 번에 4잔 이상을 얼마나 자주 마십니까?",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "없음" },
          { index: 1, value: 1, answer: "월 1회 미만" },
          { index: 2, value: 2, answer: "월 1회" },
          { index: 3, value: 3, answer: "주 1회" },
          { index: 4, value: 4, answer: "매일 또는 거의 매일" },
        ],
      },
      {
        index: 3,
        description: "지난해에 얼마나 자주 금주에 실패했습니까?",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "없음" },
          { index: 1, value: 1, answer: "월 1회 미만" },
          { index: 2, value: 2, answer: "월 1회" },
          { index: 3, value: 3, answer: "주 1회" },
          { index: 4, value: 4, answer: "매일 또는 거의 매일" },
        ],
      },
      {
        index: 4,
        description:
          "지난해에 음주 때문에 얼마나 자주 해야 할 일을 하지 못했습니까?",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "없음" },
          { index: 1, value: 1, answer: "월 1회 미만" },
          { index: 2, value: 2, answer: "월 1회" },
          { index: 3, value: 3, answer: "주 1회" },
          { index: 4, value: 4, answer: "매일 또는 거의 매일" },
        ],
      },
      {
        index: 5,
        description:
          "지난해에 심한 음주 후에 술을 깨기 위해 아침에 해장술이 필요한 경우가 얼마나 자주 있었습니까?",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "없음" },
          { index: 1, value: 1, answer: "월 1회 미만" },
          { index: 2, value: 2, answer: "월 1회" },
          { index: 3, value: 3, answer: "주 1회" },
          { index: 4, value: 4, answer: "매일 또는 거의 매일" },
        ],
      },
      {
        index: 6,
        description:
          "지난해에 음주 후에 죄책감이나 양심의 가책을 느낀 적이 얼마나 자주 있었습니까?",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "없음" },
          { index: 1, value: 1, answer: "월 1회 미만" },
          { index: 2, value: 2, answer: "월 1회" },
          { index: 3, value: 3, answer: "주 1회" },
          { index: 4, value: 4, answer: "매일 또는 거의 매일" },
        ],
      },
      {
        index: 7,
        description:
          "지난해에 음주로 인해 밤 사이에 발생한 일을 기억하지 못한 적이 얼마나 자주 있었습니까?",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "없음" },
          { index: 1, value: 1, answer: "월 1회 미만" },
          { index: 2, value: 2, answer: "월 1회" },
          { index: 3, value: 3, answer: "주 1회" },
          { index: 4, value: 4, answer: "매일 또는 거의 매일" },
        ],
      },
      {
        index: 8,
        description: "귀하의 음주 때문에 누군가가 다친 적이 있습니까?",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "없음" },
          { index: 1, value: 2, answer: "있음, 그러나 지난해가 아님" },
          { index: 2, value: 4, answer: "있음, 지난해에 있었음" },
        ],
      },
      {
        index: 9,
        description:
          "친척, 친구, 의사 또는 기타 의료 전문가가 귀하의 음주에 대해 염려하거나 술을 끊을 것을 제안한 적이 있습니까?",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "없음" },
          { index: 1, value: 2, answer: "있음, 그러나 지난해가 아님" },
          { index: 2, value: 4, answer: "있음, 지난해에 있었음" },
        ],
      },
    ],
    groups: [
      {
        id: "group1",
        title: "알코올 의존증이 얼마나 심한지를 보여주는 지표입니다",
        description:
          "현재 알코올을 얼마나 위험하게 사용하고 있는지를 보여주는 지표입니다",
        cutOffs: [
          {
            index: 0,
            end: 4,
            result: "낮은 알코올 문제 가능성",
            description:
              "알코올 사용과 관련된 건강 문제를 가지고 있을 가능성이 낮습니다. 간단한 음주교육만 필요합니다",
            severityColor: SEVERITY_COLOR.NORMAL,
          },
          {
            index: 1,
            end: 14,
            result: "가벼운 알코올 문제 가능성",
            description:
              "알코올 사용과 관련된 건강 문제의 위험도가 증가되어 있는 상태입니다. 의사와의 상담이 필요합니다",
            severityColor: SEVERITY_COLOR.MINOR,
          },
          {
            index: 2,
            end: 19,
            result: "중등도 알코올 문제 가능성",
            description:
              "알코올 사용과 관련된 건강문제의 가능성이 증가되어 있는 상태이고 경도 ~ 중등도의 알코올 의존이 있을 가능성이 있습니다. 정신과 전문의와의 상담이 필요합니다",
            severityColor: SEVERITY_COLOR.INTERMEDIATE,
          },
          {
            index: 3,
            end: 40,
            result: "심각한 알코올 문제 가능성",
            description:
              "알코올 사용과 관련된 건강문제의 가능성이 증가도어 있는 상태이고 심각한 알코올 의존이 있을 가능성이 있습니다. 정신과 전문의와의 상담이 필요합니다",
            severityColor: SEVERITY_COLOR.MAJOR,
          },
        ],
      },
    ],
    relatedArticles: [
      "https://m.blog.naver.com/hearimclinic/223178622659",
      "https://m.blog.naver.com/hearimclinic/223195459553",
      "https://m.blog.naver.com/hearimclinic/223280937983",
      "https://m.blog.naver.com/hearimclinic/223282909177",
    ],
    relatedTests: [
      "https://test.hearam.kr/test/phq9",
      "https://test.hearam.kr/test/cesd",
      "https://test.hearam.kr/test/pss",
      "https://test.hearam.kr/test/asrs",
      "https://test.hearam.kr/test/mdq",
    ],
  },
  {
    id: 6,
    name: "gad7",
    title: "일반화된 불안 장애 척도(GAD-7)",
    image: "/images/test/gad7-logo.svg",
    description:
      "일반화된 불안 장애의 증상을 평가하기 위한 7문항 자기보고식 검사입니다. 불안 증상의 심각도를 빠르게 평가하는데 유용합니다.",
    instruction: "지난 2주 동안 아래의 문제들로 인해 얼마나 자주 방해를 받았는지 답변해주세요",
    version: 1,
    date: new Date(),
    questions: [
      {
        index: 0,
        description: "초조하거나 불안하거나 가장자리에 앉아있는 느낌",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 없음" },
          { index: 1, value: 1, answer: "며칠 동안" },
          { index: 2, value: 2, answer: "7일 이상" },
          { index: 3, value: 3, answer: "거의 매일" },
        ],
      },
      {
        index: 1,
        description: "걱정을 멈추거나 조절할 수 없음",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 없음" },
          { index: 1, value: 1, answer: "며칠 동안" },
          { index: 2, value: 2, answer: "7일 이상" },
          { index: 3, value: 3, answer: "거의 매일" },
        ],
      },
      {
        index: 2,
        description: "다양한 일들에 대해 과도하게 걱정함",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 없음" },
          { index: 1, value: 1, answer: "며칠 동안" },
          { index: 2, value: 2, answer: "7일 이상" },
          { index: 3, value: 3, answer: "거의 매일" },
        ],
      },
      {
        index: 3,
        description: "편안하게 쉬기가 어려움",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 없음" },
          { index: 1, value: 1, answer: "며칠 동안" },
          { index: 2, value: 2, answer: "7일 이상" },
          { index: 3, value: 3, answer: "거의 매일" },
        ],
      },
      {
        index: 4,
        description: "너무 안절부절 못해서 가만히 앉아있기 어려움",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 없음" },
          { index: 1, value: 1, answer: "며칠 동안" },
          { index: 2, value: 2, answer: "7일 이상" },
          { index: 3, value: 3, answer: "거의 매일" },
        ],
      },
      {
        index: 5,
        description: "쉽게 짜증이 나거나 화가 남",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 없음" },
          { index: 1, value: 1, answer: "며칠 동안" },
          { index: 2, value: 2, answer: "7일 이상" },
          { index: 3, value: 3, answer: "거의 매일" },
        ],
      },
      {
        index: 6,
        description: "무언가 나쁜 일이 일어날 것처럼 두려워함",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 없음" },
          { index: 1, value: 1, answer: "며칠 동안" },
          { index: 2, value: 2, answer: "7일 이상" },
          { index: 3, value: 3, answer: "거의 매일" },
        ],
      },
    ],
    groups: [
      {
        id: "group1",
        title: "불안 장애 심각도",
        description: "불안 장애의 심각도를 나타내는 척도입니다",
        cutOffs: [
          {
            index: 0,
            end: 4,
            result: "최소한의 불안",
            description: "불안 증상이 최소한의 수준입니다",
            severityColor: SEVERITY_COLOR.NORMAL,
          },
          {
            index: 1,
            end: 9,
            result: "경도의 불안",
            description: "경도의 불안 증상이 있을 수 있습니다",
            severityColor: SEVERITY_COLOR.INTERMEDIATE,
          },
          {
            index: 2,
            end: 14,
            result: "중등도의 불안",
            description: "중등도의 불안 증상이 있을 수 있습니다",
            severityColor: SEVERITY_COLOR.WARNING,
          },
          {
            index: 3,
            end: 21,
            result: "심한 불안",
            description: "심한 불안 증상이 있을 수 있습니다. 전문가 상담을 권장합니다",
            severityColor: SEVERITY_COLOR.MAJOR,
          },
        ],
      },
    ],
    relatedArticles: [],
    relatedTests: [
      "https://test.hearam.kr/test/phq9",
      "https://test.hearam.kr/test/cesd",
      "https://test.hearam.kr/test/pss",
    ],
  },
  {
    id: 7,
    name: "pcl5",
    title: "외상후 스트레스 장애 척도(PCL-5)",
    image: "/images/test/pcl5-logo.svg",
    description:
      "외상후 스트레스 장애(PTSD) 증상을 평가하기 위한 검사입니다. 외상 경험 후 나타나는 증상의 심각도를 측정합니다.",
    instruction: "지난 한 달 동안 아래의 문제들로 인해 얼마나 자주 방해를 받았는지 답변해주세요",
    version: 1,
    date: new Date(),
    questions: [
      {
        index: 0,
        description: "예상치 못한 외상적 사건에 대한 불쾌한 기억들이 떠오름",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 없음" },
          { index: 1, value: 1, answer: "약간" },
          { index: 2, value: 2, answer: "중간 정도" },
          { index: 3, value: 3, answer: "상당히" },
          { index: 4, value: 4, answer: "극도로" },
        ],
      },
      {
        index: 1,
        description: "외상적 사건에 대한 꿈이나 악몽",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 없음" },
          { index: 1, value: 1, answer: "약간" },
          { index: 2, value: 2, answer: "중간 정도" },
          { index: 3, value: 3, answer: "상당히" },
          { index: 4, value: 4, answer: "극도로" },
        ],
      },
      {
        index: 2,
        description: "갑자기 외상적 사건이 다시 일어나는 것처럼 느껴지거나 행동함",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 없음" },
          { index: 1, value: 1, answer: "약간" },
          { index: 2, value: 2, answer: "중간 정도" },
          { index: 3, value: 3, answer: "상당히" },
          { index: 4, value: 4, answer: "극도로" },
        ],
      },
      {
        index: 3,
        description: "외상적 사건에 대해 생각하거나 말할 때 매우 불안해짐",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 없음" },
          { index: 1, value: 1, answer: "약간" },
          { index: 2, value: 2, answer: "중간 정도" },
          { index: 3, value: 3, answer: "상당히" },
          { index: 4, value: 4, answer: "극도로" },
        ],
      },
      {
        index: 4,
        description: "외상적 사건과 관련된 신체적 반응(심장 박동 증가, 숨 가쁨, 땀 등)",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 없음" },
          { index: 1, value: 1, answer: "약간" },
          { index: 2, value: 2, answer: "중간 정도" },
          { index: 3, value: 3, answer: "상당히" },
          { index: 4, value: 4, answer: "극도로" },
        ],
      },
      {
        index: 5,
        description: "외상적 사건과 관련된 생각이나 감정을 피하려고 노력함",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 없음" },
          { index: 1, value: 1, answer: "약간" },
          { index: 2, value: 2, answer: "중간 정도" },
          { index: 3, value: 3, answer: "상당히" },
          { index: 4, value: 4, answer: "극도로" },
        ],
      },
      {
        index: 6,
        description: "외상적 사건을 상기시키는 장소나 사람을 피하려고 노력함",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 없음" },
          { index: 1, value: 1, answer: "약간" },
          { index: 2, value: 2, answer: "중간 정도" },
          { index: 3, value: 3, answer: "상당히" },
          { index: 4, value: 4, answer: "극도로" },
        ],
      },
      {
        index: 7,
        description: "외상적 사건에 대한 중요한 부분을 기억하지 못함",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 없음" },
          { index: 1, value: 1, answer: "약간" },
          { index: 2, value: 2, answer: "중간 정도" },
          { index: 3, value: 3, answer: "상당히" },
          { index: 4, value: 4, answer: "극도로" },
        ],
      },
      {
        index: 8,
        description: "자신, 다른 사람, 세상에 대해 부정적인 생각이나 믿음",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 없음" },
          { index: 1, value: 1, answer: "약간" },
          { index: 2, value: 2, answer: "중간 정도" },
          { index: 3, value: 3, answer: "상당히" },
          { index: 4, value: 4, answer: "극도로" },
        ],
      },
      {
        index: 9,
        description: "외상적 사건의 원인이나 결과에 대해 자신을 비난함",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 없음" },
          { index: 1, value: 1, answer: "약간" },
          { index: 2, value: 2, answer: "중간 정도" },
          { index: 3, value: 3, answer: "상당히" },
          { index: 4, value: 4, answer: "극도로" },
        ],
      },
      {
        index: 10,
        description: "두려움, 공포, 분노, 죄책감, 수치심 같은 강한 부정적 감정",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 없음" },
          { index: 1, value: 1, answer: "약간" },
          { index: 2, value: 2, answer: "중간 정도" },
          { index: 3, value: 3, answer: "상당히" },
          { index: 4, value: 4, answer: "극도로" },
        ],
      },
      {
        index: 11,
        description: "일상 활동이나 사람들과의 관계에 관심을 잃음",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 없음" },
          { index: 1, value: 1, answer: "약간" },
          { index: 2, value: 2, answer: "중간 정도" },
          { index: 3, value: 3, answer: "상당히" },
          { index: 4, value: 4, answer: "극도로" },
        ],
      },
      {
        index: 12,
        description: "다른 사람들과 가까워지거나 가까운 관계를 유지하기 어려움",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 없음" },
          { index: 1, value: 1, answer: "약간" },
          { index: 2, value: 2, answer: "중간 정도" },
          { index: 3, value: 3, answer: "상당히" },
          { index: 4, value: 4, answer: "극도로" },
        ],
      },
      {
        index: 13,
        description: "과도한 경계 태세나 주의 깊게 주변을 살핌",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 없음" },
          { index: 1, value: 1, answer: "약간" },
          { index: 2, value: 2, answer: "중간 정도" },
          { index: 3, value: 3, answer: "상당히" },
          { index: 4, value: 4, answer: "극도로" },
        ],
      },
      {
        index: 14,
        description: "쉽게 깜짝 놀라거나 놀람",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 없음" },
          { index: 1, value: 1, answer: "약간" },
          { index: 2, value: 2, answer: "중간 정도" },
          { index: 3, value: 3, answer: "상당히" },
          { index: 4, value: 4, answer: "극도로" },
        ],
      },
      {
        index: 15,
        description: "집중하기 어려움",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 없음" },
          { index: 1, value: 1, answer: "약간" },
          { index: 2, value: 2, answer: "중간 정도" },
          { index: 3, value: 3, answer: "상당히" },
          { index: 4, value: 4, answer: "극도로" },
        ],
      },
      {
        index: 16,
        description: "잠들기 어렵거나 잠을 유지하기 어려움",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 없음" },
          { index: 1, value: 1, answer: "약간" },
          { index: 2, value: 2, answer: "중간 정도" },
          { index: 3, value: 3, answer: "상당히" },
          { index: 4, value: 4, answer: "극도로" },
        ],
      },
      {
        index: 17,
        description: "과도한 짜증이나 분노 폭발",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 없음" },
          { index: 1, value: 1, answer: "약간" },
          { index: 2, value: 2, answer: "중간 정도" },
          { index: 3, value: 3, answer: "상당히" },
          { index: 4, value: 4, answer: "극도로" },
        ],
      },
      {
        index: 18,
        description: "위험한 행동을 함",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 없음" },
          { index: 1, value: 1, answer: "약간" },
          { index: 2, value: 2, answer: "중간 정도" },
          { index: 3, value: 3, answer: "상당히" },
          { index: 4, value: 4, answer: "극도로" },
        ],
      },
    ],
    groups: [
      {
        id: "group1",
        title: "PTSD 심각도",
        description: "외상후 스트레스 장애의 심각도를 나타내는 척도입니다",
        cutOffs: [
          {
            index: 0,
            end: 10,
            result: "최소한의 증상",
            description: "PTSD 증상이 최소한의 수준입니다",
            severityColor: SEVERITY_COLOR.NORMAL,
          },
          {
            index: 1,
            end: 20,
            result: "경도의 증상",
            description: "경도의 PTSD 증상이 있을 수 있습니다",
            severityColor: SEVERITY_COLOR.INTERMEDIATE,
          },
          {
            index: 2,
            end: 33,
            result: "중등도의 증상",
            description: "중등도의 PTSD 증상이 있을 수 있습니다",
            severityColor: SEVERITY_COLOR.WARNING,
          },
          {
            index: 3,
            end: 51,
            result: "심한 증상",
            description: "심한 PTSD 증상이 있을 수 있습니다. 전문가 상담을 권장합니다",
            severityColor: SEVERITY_COLOR.MAJOR,
          },
          {
            index: 4,
            end: 80,
            result: "매우 심한 증상",
            description: "매우 심한 PTSD 증상이 있을 수 있습니다. 즉시 전문가 상담을 권장합니다",
            severityColor: SEVERITY_COLOR.CRITICAL,
          },
        ],
      },
    ],
    relatedArticles: [],
    relatedTests: [
      "https://test.hearam.kr/test/phq9",
      "https://test.hearam.kr/test/gad7",
      "https://test.hearam.kr/test/pss",
    ],
  },
  {
    id: 8,
    name: "who5",
    title: "WHO 웰빙 지수(WHO-5 Well-being Index)",
    image: "/images/test/who5-logo.svg",
    description:
      "정신적 웰빙을 측정하기 위한 간단한 검사입니다. 긍정적 정신 건강의 지표로 사용됩니다.",
    instruction: "지난 2주 동안 아래의 항목들이 얼마나 자주 해당되었는지 답변해주세요",
    version: 1,
    date: new Date(),
    questions: [
      {
        index: 0,
        description: "나는 기분이 좋고 경쾌했다",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 5, answer: "항상" },
          { index: 1, value: 4, answer: "대부분" },
          { index: 2, value: 3, answer: "절반 이상" },
          { index: 3, value: 2, answer: "때때로" },
          { index: 4, value: 1, answer: "전혀 없음" },
          { index: 5, value: 0, answer: "전혀 없음" },
        ],
      },
      {
        index: 1,
        description: "나는 평온하고 편안했다",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 5, answer: "항상" },
          { index: 1, value: 4, answer: "대부분" },
          { index: 2, value: 3, answer: "절반 이상" },
          { index: 3, value: 2, answer: "때때로" },
          { index: 4, value: 1, answer: "전혀 없음" },
          { index: 5, value: 0, answer: "전혀 없음" },
        ],
      },
      {
        index: 2,
        description: "나는 활력이 넘쳤다",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 5, answer: "항상" },
          { index: 1, value: 4, answer: "대부분" },
          { index: 2, value: 3, answer: "절반 이상" },
          { index: 3, value: 2, answer: "때때로" },
          { index: 4, value: 1, answer: "전혀 없음" },
          { index: 5, value: 0, answer: "전혀 없음" },
        ],
      },
      {
        index: 3,
        description: "나는 깨어있고 새롭게 느꼈다",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 5, answer: "항상" },
          { index: 1, value: 4, answer: "대부분" },
          { index: 2, value: 3, answer: "절반 이상" },
          { index: 3, value: 2, answer: "때때로" },
          { index: 4, value: 1, answer: "전혀 없음" },
          { index: 5, value: 0, answer: "전혀 없음" },
        ],
      },
      {
        index: 4,
        description: "내 일상생활이 흥미롭게 느껴졌다",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 5, answer: "항상" },
          { index: 1, value: 4, answer: "대부분" },
          { index: 2, value: 3, answer: "절반 이상" },
          { index: 3, value: 2, answer: "때때로" },
          { index: 4, value: 1, answer: "전혀 없음" },
          { index: 5, value: 0, answer: "전혀 없음" },
        ],
      },
    ],
    groups: [
      {
        id: "group1",
        title: "웰빙 점수",
        description: "정신적 웰빙 수준을 나타내는 척도입니다 (0-100점)",
        cutOffs: [
          {
            index: 0,
            end: 50,
            result: "낮은 웰빙",
            description: "웰빙 수준이 낮습니다. 전문가 상담을 고려해보세요",
            severityColor: SEVERITY_COLOR.MAJOR,
          },
          {
            index: 1,
            end: 69,
            result: "보통 웰빙",
            description: "웰빙 수준이 보통입니다",
            severityColor: SEVERITY_COLOR.INTERMEDIATE,
          },
          {
            index: 2,
            end: 100,
            result: "높은 웰빙",
            description: "웰빙 수준이 높습니다",
            severityColor: SEVERITY_COLOR.NORMAL,
          },
        ],
      },
    ],
    relatedArticles: [],
    relatedTests: [
      "https://test.hearam.kr/test/phq9",
      "https://test.hearam.kr/test/cesd",
      "https://test.hearam.kr/test/pss",
    ],
  },
  {
    id: 9,
    name: "epds",
    title: "에딘버러 산후 우울증 척도(EPDS)",
    image: "/images/test/epds-logo.svg",
    description:
      "산후 우울증을 선별하기 위한 검사입니다. 출산 후 여성의 우울 증상을 평가하는데 사용됩니다.",
    instruction: "지난 7일 동안 아래의 항목들이 얼마나 자주 해당되었는지 답변해주세요",
    version: 1,
    date: new Date(),
    questions: [
      {
        index: 0,
        description: "나는 웃을 수 있었고, 웃긴 일의 재미있는 면을 볼 수 있었다",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "항상 그랬다" },
          { index: 1, value: 1, answer: "대부분 그랬다" },
          { index: 2, value: 2, answer: "가끔 그랬다" },
          { index: 3, value: 3, answer: "전혀 그렇지 않았다" },
        ],
      },
      {
        index: 1,
        description: "나는 앞으로 일어날 일을 기대했다",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "항상 그랬다" },
          { index: 1, value: 1, answer: "대부분 그랬다" },
          { index: 2, value: 2, answer: "가끔 그랬다" },
          { index: 3, value: 3, answer: "전혀 그렇지 않았다" },
        ],
      },
      {
        index: 2,
        description: "나는 불필요하게 걱정했다",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 그렇지 않았다" },
          { index: 1, value: 1, answer: "가끔 그랬다" },
          { index: 2, value: 2, answer: "대부분 그랬다" },
          { index: 3, value: 3, answer: "항상 그랬다" },
        ],
      },
      {
        index: 3,
        description: "나는 불안하거나 걱정 없이 있었다",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "항상 그랬다" },
          { index: 1, value: 1, answer: "대부분 그랬다" },
          { index: 2, value: 2, answer: "가끔 그랬다" },
          { index: 3, value: 3, answer: "전혀 그렇지 않았다" },
        ],
      },
      {
        index: 4,
        description: "나는 두려움을 느꼈다",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 그렇지 않았다" },
          { index: 1, value: 1, answer: "가끔 그랬다" },
          { index: 2, value: 2, answer: "대부분 그랬다" },
          { index: 3, value: 3, answer: "항상 그랬다" },
        ],
      },
      {
        index: 5,
        description: "나는 일들이 너무 많이 쌓여서 대처하기 어려웠다",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 그렇지 않았다" },
          { index: 1, value: 1, answer: "가끔 그랬다" },
          { index: 2, value: 2, answer: "대부분 그랬다" },
          { index: 3, value: 3, answer: "항상 그랬다" },
        ],
      },
      {
        index: 6,
        description: "나는 불행해서 잠을 잘 수 없었다",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 그렇지 않았다" },
          { index: 1, value: 1, answer: "가끔 그랬다" },
          { index: 2, value: 2, answer: "대부분 그랬다" },
          { index: 3, value: 3, answer: "항상 그랬다" },
        ],
      },
      {
        index: 7,
        description: "나는 슬프거나 불행했다",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 그렇지 않았다" },
          { index: 1, value: 1, answer: "가끔 그랬다" },
          { index: 2, value: 2, answer: "대부분 그랬다" },
          { index: 3, value: 3, answer: "항상 그랬다" },
        ],
      },
      {
        index: 8,
        description: "나는 불행해서 울었다",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 그렇지 않았다" },
          { index: 1, value: 1, answer: "가끔 그랬다" },
          { index: 2, value: 2, answer: "대부분 그랬다" },
          { index: 3, value: 3, answer: "항상 그랬다" },
        ],
      },
      {
        index: 9,
        description: "나는 자신을 해치는 생각을 했다",
        group: "group1",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 그렇지 않았다" },
          { index: 1, value: 1, answer: "가끔 그랬다" },
          { index: 2, value: 2, answer: "대부분 그랬다" },
          { index: 3, value: 3, answer: "항상 그랬다" },
        ],
      },
    ],
    groups: [
      {
        id: "group1",
        title: "산후 우울증 심각도",
        description: "산후 우울증의 심각도를 나타내는 척도입니다",
        cutOffs: [
          {
            index: 0,
            end: 9,
            result: "우울증 없음",
            description: "산후 우울증 증상이 없습니다",
            severityColor: SEVERITY_COLOR.NORMAL,
          },
          {
            index: 1,
            end: 12,
            result: "경도의 우울증",
            description: "경도의 산후 우울증 증상이 있을 수 있습니다",
            severityColor: SEVERITY_COLOR.INTERMEDIATE,
          },
          {
            index: 2,
            end: 30,
            result: "중등도 이상의 우울증",
            description: "중등도 이상의 산후 우울증 증상이 있을 수 있습니다. 전문가 상담을 권장합니다",
            severityColor: SEVERITY_COLOR.MAJOR,
          },
        ],
      },
    ],
    relatedArticles: [],
    relatedTests: [
      "https://test.hearam.kr/test/phq9",
      "https://test.hearam.kr/test/cesd",
      "https://test.hearam.kr/test/gad7",
    ],
  },
  {
    id: 10,
    name: "dass21",
    title: "우울·불안·스트레스 척도(DASS-21)",
    image: "/images/test/dass21-logo.svg",
    description:
      "우울, 불안, 스트레스의 세 가지 정서 상태를 종합적으로 평가하는 검사입니다. 21문항으로 구성되어 있습니다.",
    instruction: "지난 일주일 동안 아래의 항목들이 얼마나 자주 해당되었는지 답변해주세요",
    version: 1,
    date: new Date(),
    questions: [
      {
        index: 0,
        description: "나는 평소에 느끼지 못했던 감정의 변화를 느꼈다",
        group: "depression",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 해당 없음" },
          { index: 1, value: 1, answer: "때때로 또는 가끔" },
          { index: 2, value: 2, answer: "상당히 자주" },
          { index: 3, value: 3, answer: "거의 항상 또는 항상" },
        ],
      },
      {
        index: 1,
        description: "나는 무언가를 느끼는 능력이 없어 보였다",
        group: "depression",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 해당 없음" },
          { index: 1, value: 1, answer: "때때로 또는 가끔" },
          { index: 2, value: 2, answer: "상당히 자주" },
          { index: 3, value: 3, answer: "거의 항상 또는 항상" },
        ],
      },
      {
        index: 2,
        description: "나는 긍정적인 감정을 느끼기 어려웠다",
        group: "depression",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 해당 없음" },
          { index: 1, value: 1, answer: "때때로 또는 가끔" },
          { index: 2, value: 2, answer: "상당히 자주" },
          { index: 3, value: 3, answer: "거의 항상 또는 항상" },
        ],
      },
      {
        index: 3,
        description: "나는 초조함을 느꼈다",
        group: "anxiety",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 해당 없음" },
          { index: 1, value: 1, answer: "때때로 또는 가끔" },
          { index: 2, value: 2, answer: "상당히 자주" },
          { index: 3, value: 3, answer: "거의 항상 또는 항상" },
        ],
      },
      {
        index: 4,
        description: "나는 마른 입을 느꼈다",
        group: "anxiety",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 해당 없음" },
          { index: 1, value: 1, answer: "때때로 또는 가끔" },
          { index: 2, value: 2, answer: "상당히 자주" },
          { index: 3, value: 3, answer: "거의 항상 또는 항상" },
        ],
      },
      {
        index: 5,
        description: "나는 숨을 쉬기 어렵다고 느꼈다",
        group: "anxiety",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 해당 없음" },
          { index: 1, value: 1, answer: "때때로 또는 가끔" },
          { index: 2, value: 2, answer: "상당히 자주" },
          { index: 3, value: 3, answer: "거의 항상 또는 항상" },
        ],
      },
      {
        index: 6,
        description: "나는 일상적인 일을 하는데 어려움을 느꼈다",
        group: "stress",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 해당 없음" },
          { index: 1, value: 1, answer: "때때로 또는 가끔" },
          { index: 2, value: 2, answer: "상당히 자주" },
          { index: 3, value: 3, answer: "거의 항상 또는 항상" },
        ],
      },
      {
        index: 7,
        description: "나는 과도하게 반응했다고 느꼈다",
        group: "stress",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 해당 없음" },
          { index: 1, value: 1, answer: "때때로 또는 가끔" },
          { index: 2, value: 2, answer: "상당히 자주" },
          { index: 3, value: 3, answer: "거의 항상 또는 항상" },
        ],
      },
      {
        index: 8,
        description: "나는 떨림을 느꼈다",
        group: "anxiety",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 해당 없음" },
          { index: 1, value: 1, answer: "때때로 또는 가끔" },
          { index: 2, value: 2, answer: "상당히 자주" },
          { index: 3, value: 3, answer: "거의 항상 또는 항상" },
        ],
      },
      {
        index: 9,
        description: "나는 걱정으로 인해 많은 에너지를 소비했다고 느꼈다",
        group: "anxiety",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 해당 없음" },
          { index: 1, value: 1, answer: "때때로 또는 가끔" },
          { index: 2, value: 2, answer: "상당히 자주" },
          { index: 3, value: 3, answer: "거의 항상 또는 항상" },
        ],
      },
      {
        index: 10,
        description: "나는 미래에 대해 낙관적이지 않다고 느꼈다",
        group: "depression",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 해당 없음" },
          { index: 1, value: 1, answer: "때때로 또는 가끔" },
          { index: 2, value: 2, answer: "상당히 자주" },
          { index: 3, value: 3, answer: "거의 항상 또는 항상" },
        ],
      },
      {
        index: 11,
        description: "나는 불안했다",
        group: "anxiety",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 해당 없음" },
          { index: 1, value: 1, answer: "때때로 또는 가끔" },
          { index: 2, value: 2, answer: "상당히 자주" },
          { index: 3, value: 3, answer: "거의 항상 또는 항상" },
        ],
      },
      {
        index: 12,
        description: "나는 가치가 없다고 느꼈다",
        group: "depression",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 해당 없음" },
          { index: 1, value: 1, answer: "때때로 또는 가끔" },
          { index: 2, value: 2, answer: "상당히 자주" },
          { index: 3, value: 3, answer: "거의 항상 또는 항상" },
        ],
      },
      {
        index: 13,
        description: "나는 쉽게 화를 냈다",
        group: "stress",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 해당 없음" },
          { index: 1, value: 1, answer: "때때로 또는 가끔" },
          { index: 2, value: 2, answer: "상당히 자주" },
          { index: 3, value: 3, answer: "거의 항상 또는 항상" },
        ],
      },
      {
        index: 14,
        description: "나는 차분하게 머물기 어려웠다",
        group: "anxiety",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 해당 없음" },
          { index: 1, value: 1, answer: "때때로 또는 가끔" },
          { index: 2, value: 2, answer: "상당히 자주" },
          { index: 3, value: 3, answer: "거의 항상 또는 항상" },
        ],
      },
      {
        index: 15,
        description: "나는 활력을 느끼기 어려웠다",
        group: "depression",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 해당 없음" },
          { index: 1, value: 1, answer: "때때로 또는 가끔" },
          { index: 2, value: 2, answer: "상당히 자주" },
          { index: 3, value: 3, answer: "거의 항상 또는 항상" },
        ],
      },
      {
        index: 16,
        description: "나는 상황을 다루기 어렵다고 느꼈다",
        group: "stress",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 해당 없음" },
          { index: 1, value: 1, answer: "때때로 또는 가끔" },
          { index: 2, value: 2, answer: "상당히 자주" },
          { index: 3, value: 3, answer: "거의 항상 또는 항상" },
        ],
      },
      {
        index: 17,
        description: "나는 우울했다",
        group: "depression",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 해당 없음" },
          { index: 1, value: 1, answer: "때때로 또는 가끔" },
          { index: 2, value: 2, answer: "상당히 자주" },
          { index: 3, value: 3, answer: "거의 항상 또는 항상" },
        ],
      },
      {
        index: 18,
        description: "나는 불필요한 걱정을 했다",
        group: "anxiety",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 해당 없음" },
          { index: 1, value: 1, answer: "때때로 또는 가끔" },
          { index: 2, value: 2, answer: "상당히 자주" },
          { index: 3, value: 3, answer: "거의 항상 또는 항상" },
        ],
      },
      {
        index: 19,
        description: "나는 즐거움을 느끼기 어려웠다",
        group: "depression",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 해당 없음" },
          { index: 1, value: 1, answer: "때때로 또는 가끔" },
          { index: 2, value: 2, answer: "상당히 자주" },
          { index: 3, value: 3, answer: "거의 항상 또는 항상" },
        ],
      },
      {
        index: 20,
        description: "나는 쉽게 화를 냈다",
        group: "stress",
        type: "radio",
        currentItemIndex: null,
        currentValue: null,
        answers: [
          { index: 0, value: 0, answer: "전혀 해당 없음" },
          { index: 1, value: 1, answer: "때때로 또는 가끔" },
          { index: 2, value: 2, answer: "상당히 자주" },
          { index: 3, value: 3, answer: "거의 항상 또는 항상" },
        ],
      },
    ],
    groups: [
      {
        id: "depression",
        title: "우울 점수",
        description: "우울 증상의 심각도를 나타내는 척도입니다 (0-42점)",
        cutOffs: [
          {
            index: 0,
            end: 9,
            result: "정상",
            description: "우울 증상이 정상 범위입니다",
            severityColor: SEVERITY_COLOR.NORMAL,
          },
          {
            index: 1,
            end: 13,
            result: "경도",
            description: "경도의 우울 증상이 있습니다",
            severityColor: SEVERITY_COLOR.INTERMEDIATE,
          },
          {
            index: 2,
            end: 20,
            result: "중등도",
            description: "중등도의 우울 증상이 있습니다",
            severityColor: SEVERITY_COLOR.WARNING,
          },
          {
            index: 3,
            end: 27,
            result: "심각",
            description: "심각한 우울 증상이 있습니다",
            severityColor: SEVERITY_COLOR.MAJOR,
          },
          {
            index: 4,
            end: 42,
            result: "매우 심각",
            description: "매우 심각한 우울 증상이 있습니다. 전문가 상담을 권장합니다",
            severityColor: SEVERITY_COLOR.CRITICAL,
          },
        ],
      },
      {
        id: "anxiety",
        title: "불안 점수",
        description: "불안 증상의 심각도를 나타내는 척도입니다 (0-42점)",
        cutOffs: [
          {
            index: 0,
            end: 7,
            result: "정상",
            description: "불안 증상이 정상 범위입니다",
            severityColor: SEVERITY_COLOR.NORMAL,
          },
          {
            index: 1,
            end: 9,
            result: "경도",
            description: "경도의 불안 증상이 있습니다",
            severityColor: SEVERITY_COLOR.INTERMEDIATE,
          },
          {
            index: 2,
            end: 14,
            result: "중등도",
            description: "중등도의 불안 증상이 있습니다",
            severityColor: SEVERITY_COLOR.WARNING,
          },
          {
            index: 3,
            end: 19,
            result: "심각",
            description: "심각한 불안 증상이 있습니다",
            severityColor: SEVERITY_COLOR.MAJOR,
          },
          {
            index: 4,
            end: 42,
            result: "매우 심각",
            description: "매우 심각한 불안 증상이 있습니다. 전문가 상담을 권장합니다",
            severityColor: SEVERITY_COLOR.CRITICAL,
          },
        ],
      },
      {
        id: "stress",
        title: "스트레스 점수",
        description: "스트레스 증상의 심각도를 나타내는 척도입니다 (0-42점)",
        cutOffs: [
          {
            index: 0,
            end: 14,
            result: "정상",
            description: "스트레스 수준이 정상 범위입니다",
            severityColor: SEVERITY_COLOR.NORMAL,
          },
          {
            index: 1,
            end: 18,
            result: "경도",
            description: "경도의 스트레스가 있습니다",
            severityColor: SEVERITY_COLOR.INTERMEDIATE,
          },
          {
            index: 2,
            end: 25,
            result: "중등도",
            description: "중등도의 스트레스가 있습니다",
            severityColor: SEVERITY_COLOR.WARNING,
          },
          {
            index: 3,
            end: 33,
            result: "심각",
            description: "심각한 스트레스가 있습니다",
            severityColor: SEVERITY_COLOR.MAJOR,
          },
          {
            index: 4,
            end: 42,
            result: "매우 심각",
            description: "매우 심각한 스트레스가 있습니다. 전문가 상담을 권장합니다",
            severityColor: SEVERITY_COLOR.CRITICAL,
          },
        ],
      },
    ],
    relatedArticles: [],
    relatedTests: [
      "https://test.hearam.kr/test/phq9",
      "https://test.hearam.kr/test/cesd",
      "https://test.hearam.kr/test/gad7",
      "https://test.hearam.kr/test/pss",
    ],
  },
];

export default questionnaires;
